# Generated by Django 4.2 on 2023-12-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_productminimal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productminimal',
            old_name='product',
            new_name='product_id',
        ),
    ]
