# Generated by Django 4.2 on 2023-07-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_explenation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MealInCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.categorymenu')),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_pices_used', models.DecimalField(decimal_places=3, max_digits=10)),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.product')),
            ],
        ),
    ]
