# Generated by Django 4.2 on 2023-07-31 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealincategory',
            options={'permissions': [('codename', 'mealincategory')]},
        ),
    ]
