# Generated by Django 4.2 on 2023-07-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_mealincategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymenu',
            options={'permissions': [('codename', 'categorymenu')]},
        ),
    ]
