# Generated by Django 4.2 on 2024-01-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_categorymenu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymenu',
            name='category_show',
            field=models.BooleanField(default=True),
        ),
    ]
