# Generated by Django 4.2 on 2023-08-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterorder',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
