# Generated by Django 4.2 on 2023-12-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_waiterorder_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogedWaiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_logged', models.BooleanField(default=False)),
                ('waiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waiter.waiter')),
            ],
        ),
    ]
