# Generated by Django 4.2 on 2023-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0003_logedwaiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='logedwaiter',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
