# Generated by Django 4.2 on 2023-07-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230731_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('none', 'none'), ('waiters', 'regular'), ('kitchen', 'subscriber'), ('manager', 'moderator'), ('owner', 'owner')], default='none', max_length=100),
        ),
    ]
