# Generated by Django 4.2 on 2023-07-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
