# Generated by Django 4.2 on 2023-08-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('tier_1', 'Can view 3 suggestions'), ('tier_2', 'Can view 6 suggestions'))},
        ),
    ]
