# Generated by Django 4.2 on 2023-12-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loginnumber',
            field=models.IntegerField(default=1111),
        ),
    ]
